title: Todd Schaffer # your name (or website title) here
logo: "images/rsz_schaffertodd190822004.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Here is a list of past projects I have worked on. I would be happy to answer any questions you may have.
  <br><br>
  <a href="https://www.linkedin.com/in/todd-schaffer/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal

