title: Todd Schaffer # your name (or website title) here
logo: "images/SchafferTodd190822004.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  First description 
  I am a passionate about analyzing the statistical signficance in data. Please feel free
  to explore some of my past projects I have worked on. Thank you for your time!
  <br><br>
  <a href="https://www.linkedin.com/in/todd-schaffer/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
