title: Todd Schaffer # your name (or website title) here
logo: "images/SchafferTodd190822004.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  First description 
  <br><br>
  <br><br>
  <br><br>
  Second description 
  <br><br>
  <br><br>
  <a href="https://www.linkedin.com/in/todd-schaffer/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
